version: "3"
services:
  web:
    image: nginx:alpine
    volumes:
      - ./mnt/flarum:/var/www
      - ./mnt/nginx/conf.d/flarum.conf:/etc/nginx/conf.d/default.conf
      - ./mnt/nginx/conf.d/.nginx.conf:/etc/nginx/conf.d/.nginx.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
    - "80:80"
    - "443:443"
    networks:
      - code-network
    depends_on:
      - php
      
  certbot:
        image: certbot/certbot
        restart: unless-stopped
        volumes:
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  php:
    build:
      context: .
      dockerfile: flarum-fpm.dockerfile
    image: flarum-fpm:1
    volumes:
      - ./mnt/flarum:/var/www
    networks: 
      - code-network
      - db-network
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.4
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=flarum
      - MYSQL_USER=flarum
      - MYSQL_PASSWORD=flarumpass
    volumes:
      - ./mnt/mysql/db:/var/lib/mysql
    networks: 
      - db-network

networks:
    code-network:
        driver: bridge
    db-network:
      driver: bridge

volumes:
  db:
